/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "CERT_ARN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SANITY_PROJECT_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "lysfjord": {
      "type": "sst.aws.SvelteKit"
      "url": string
    }
  }
}

import "sst"
export {}